name: skipapp-showcase
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: '30 3,8,15,20 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-app.yml@main
    secrets:
      # These optional secrets enable the Android app to be signed
      KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
      KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      GOOGLE_PLAY_APIKEY: ${{ secrets.GOOGLE_PLAY_APIKEY }}

